#cloud-config

write_files:
  - path: /root/join-cluster.sh
    permissions: 0755
    content: |
      #!/bin/bash
      HOSTNAME=`hostname`
      # get the  cluster token
      TOKEN=$(wget -nv -q -O - --retry-connrefused --tries=0 --waitretry 5 http://master0:1337/join/$HOSTNAME)
      # TODO: clean this up
      curl -sfL https://get.k3s.io | K3S_URL=https://master0:6443 K3S_TOKEN=$TOKEN sh -
  - path: /root/leave-cluster.sh
    permissions: 0755
    content: |
      #!/bin/bash
      HOSTNAME=`hostname`
      # signal the master to drain services from our node
      wget -nv -q -O - --retry-connrefused --tries=10 --waitretry 5 http://master0:1337/drain/$HOSTNAME
  - path: /etc/systemd/system/k3s-join.service
    permissions: 0444
    content: |
      [Unit]
      Description=Join k3s cluster
      DefaultDependencies=no
      After=multi-user.target
      [Service]
      Type=oneshot
      ExecStart=/root/join-cluster.sh
      [Install]
      WantedBy=multi-user.target
  - path: /etc/systemd/system/k3s-leave.service
    permissions: 0444
    content: |
      [Unit]
      Description=Leave k3s cluster
      DefaultDependencies=no
      Before=shutdown.target reboot.target halt.target
      [Service]
      Type=oneshot
      ExecStart=/root/leave-cluster.sh
      [Install]
      WantedBy=halt.target reboot.target shutdown.target
  - path: /etc/waagent.conf
    permissions: 0444
    content: |
      ResourceDisk.Format=y
      ResourceDisk.Filesystem=ext4
      ResourceDisk.MountPoint=/mnt/resource
      ResourceDisk.EnableSwap=y
      ResourceDisk.SwapSizeMB=2048
  - path: /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl
    permissions: 0444
    content: |
      [plugins.opt]
      path = "{{ .NodeConfig.Containerd.Opt }}"
      
      [plugins.cri]
      stream_server_address = "{{ .NodeConfig.AgentConfig.NodeName }}"
      stream_server_port = "10010"
        [plugins.cri.cni]
          bin_dir = "{{ .NodeConfig.AgentConfig.CNIBinDir }}"
          conf_dir = "{{ .NodeConfig.AgentConfig.CNIConfDir }}"
      
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
        [plugins.cri.registry.mirrors."master0:5000"]
          endpoint = ["http://master0:5000"]

mounts:
  - - //${STORAGE_ACCOUNT_NAME}.file.core.windows.net/${SHARE_NAME}
    - /srv
    - cifs
    - vers=3.0,username=${STORAGE_ACCOUNT_NAME},password=${STORAGE_ACCOUNT_KEY},dir_mode=0770,file_mode=0660,uid=1000,gid=1000,noperm,mfsymlinks,iocharset=utf8

apt_update: true
apt_upgrade: true

packages:
  - ntp
  #- tmux
  #- htop
  #- vim
  - fail2ban
  #- curl

runcmd:
  - systemctl enable k3s-join
  - systemctl enable k3s-leave
  #- systemctl start k3s-leave
  #- systemctl start k3s-join
  - reboot