#cloud-config

write_files:
  - path: /root/join-cluster.sh
    permissions: 0755
    content: |
      #!/bin/bash
      HOSTNAME=`hostname`
      # get the  cluster token
      TOKEN=$(wget -nv -q -O - --retry-connrefused 20 --waitretry 5 http://master0:1337/join/$HOSTNAME)
      # TODO: clean this up
      curl -sfL https://get.k3s.io | K3S_URL=https://master0:6443 K3S_TOKEN=$TOKEN sh -
  - path: /root/leave-cluster.sh
    permissions: 0755
    content: |
      #!/bin/bash
      HOSTNAME=`hostname`
      # signal the master to drain services from our node
      wget -nv -q -O - --retry-connrefused 20 --waitretry 5 http://master0:1337/drain/$HOSTNAME
  - path: /etc/systemd/system/k3s-join.service
    permissions: 0444
    content: |
      [Unit]
      Description=Join k3s cluster
      DefaultDependencies=no
      After=multi-user.target
      [Service]
      Type=oneshot
      ExecStart=/root/join-cluster.sh
      [Install]
      WantedBy=multi-user.target
  - path: /etc/systemd/system/k3s-leave.service
    permissions: 0444
    content: |
      [Unit]
      Description=Leave k3s cluster
      DefaultDependencies=no
      Before=shutdown.target reboot.target halt.target
      [Service]
      Type=oneshot
      ExecStart=/root/leave-cluster.sh
      [Install]
      WantedBy=halt.target reboot.target shutdown.target
  - path: /etc/waagent.conf
    permissions: 0444
    content: |
      ResourceDisk.Format=y
      ResourceDisk.Filesystem=ext4
      ResourceDisk.MountPoint=/mnt/resource
      ResourceDisk.EnableSwap=y
      ResourceDisk.SwapSizeMB=2048

mounts:
  - - //${STORAGE_ACCOUNT_NAME}.file.core.windows.net/${SHARE_NAME}
    - /srv
    - cifs
    - vers=3.0,username=${STORAGE_ACCOUNT_NAME},password=${STORAGE_ACCOUNT_KEY},dir_mode=0770,file_mode=0660,uid=1000,gid=1000,noperm,,iocharset=utf8

#apt_update: true
#apt_upgrade: true

packages:
  - ntp
  #- tmux
  #- htop
  #- vim
  - fail2ban
  #- curl

runcmd:
  - systemctl enable k3s-join
  - systemctl enable k3s-leave
  - systemctl start k3s-leave
  - systemctl start k3s-join
  #- reboot